module.exports = {
  commanMessage: {
    PASSWORD_RESET: "Password reset successfully",
    VERIFY_OTP: "Verify Otp Successfully",
    REGISTER_OTP_VERIFY: "Registeration Verify Successfully",
    SOMETHING_WENT_WRONG: "Something went wrong",
    PASSWORD_RESET: "Password reset successful",
    VALIDATION_FAILED: "Validation Failed",
    TOKEN_MISSING: "Token is Missing, Must send Token",
    INVALID_TOKEN: "Token is Invalid",
    EMAIL_NOT_MATCHED: "Email not matched",
    PASSWORD_NOT_MATCHED: "Password not matched",
    ADMIN_LOGIN_SUCCESS: "Admin login successfully",
    COACHING_LOGIN_SUCCESS: "Coaching login successfully",
    EMAIL_REQUIRED: "Email is required",
    INVALID_ID: "Invalid User ID",
    ALL_FIELD_REQUIRED: "All field are required",
    VALIDATION_FAILED: "Opps ! validation failed",
    EMAIL_ALREADY_EXIST: "Email already exist",
    OTP_RESEND: "Resend Your Otp",
    OTP_SEND_SUCCESSFULLY: "Otp send successfully",
    PASSWORD_UPDATED: "Password Updated Successfully!",
    PASSWORD_NOT_UPDATED: "OOPS ! Password Not Updated !",
  },

  adminMessage: {
    OTP_INVALID: "Your OTP id Invalid",
    ADMIN_CREATED: "Admin Register Successfully and You Need To Verify The Otp",
    ADMIN_NOT_CREATED: "Admin Not Created",
    EMAIL_AND_PASSWORD_NOT_MATCH: "Email and password is not match",
    OLD_PASSWORD_NOT_MATCHED: "OOPS ! Old Password is not Matched !",
    PROFILE_NOT_UPDATED: "OOPS ! Profile Not Updated !",
    PROFILE_UPDATED: "Profile Updated Successfully !",
    PROFILE_FETCHED: "Profile Fetched Successfully !",
    ACCOUNT_FOUND: "Account Found Successfully !",
    ACCOUNT_NOT_FOUND: "Account Not Found !",
    PROFILE_NOT_FETCHED: "OOPS ! Profile Not Fetched !",
    ADMIN_NOT_FOUND: "Admin not found",
    ADMIN_DELETE: "Admin delete",
    ADMIN_NOT_FETCHED: "Admin not fetched !",
    ADMIN_FETCHED: "Admin fetched !",

    ADMIN_NOT_UPDATED: "Admin not updated !",
    ADMIN_UPDATED: "Admin updated !",
  },

  batchMessage: {
    BATCH_CREATED: "Batch Created Successfully !",
    BATCH_DELETED: "Batch Deleted Successfully !",
    BATCH_EXIST: "Batch already exist",
    BATCH_NOT_FOUND: "Batch not found",
    BATCH_UPDATED_SUCCESSFULLY: "Batch Updated successfully",
    BATCH_GET_SUCCESSFULLY: "Batch get successfully",
    ALL_BATCH_GET_SUCCESSFULLY: "All Batch get successfully",
  },
  studentFeesMessage: {
    STUDENT_FEES_CREATED: "Student Fees Created Successfully !",
    STUDENT_FEES_DELETED: "Student  Fees Deleted Successfully !",
    STUDENT_FEES_EXIST: "Student  Fees already exist",
    STUDENT_FEES_NOT_FOUND: "Student  Fees not found",
    STUDENT_FEES_UPDATED_SUCCESSFULLY: "Student  Fees Updated successfully",
    STUDENT_FEES_GET_SUCCESSFULLY: "Student  Fees get successfully",
    ALL_STUDENT_FEES_GET_SUCCESSFULLY: "All  Fees Of Student get successfully",
  },
  studentMessage: {
    STUDENT_CREATED: "Student Created Successfully !",
    STUDENT_DELETED: "Student Deleted Successfully !",
    STUDENT_EXIST: "Student already exist",
    STUDENT_NOT_FOUND: "Student not found",
    STUDENT_UPDATED_SUCCESSFULLY: "Student Updated successfully",
    STUDENT_GET_SUCCESSFULLY: "Student get successfully",
    ALL_STUDENT_GET_SUCCESSFULLY: "All Student get successfully",
  },
};
